# Generated by Django 5.1.6 on 2025-02-26 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_foldercategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="UrlList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("link", models.URLField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "folder_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.foldercategory",
                    ),
                ),
            ],
        ),
    ]
