# Generated by Django 5.1.6 on 2025-03-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_urllist"),
    ]

    operations = [
        migrations.AddField(
            model_name="urllist",
            name="image",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
