# Generated by Django 5.1.6 on 2025-03-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_urllist_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urllist", name="image", field=models.TextField(),
        ),
    ]
