# Generated by Django 5.1.6 on 2025-04-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_urllist_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urllist",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
